{
  pkgs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    android-tools
    ani-cli
    anitr-cli
    antimicrox
    anup
    atuin
    audacity
    bat
    bat-extras.core
    bats
    better-control
    bleachbit
    bolt-launcher
    btrfs-progs
    bubblewrap
    comma
    crow-translate
    curl
    dash
    deadnix
    easyeffects
    efibootmgr
    exiftool
    eza
    fastfetch
    ffmpeg-full
    flameshot
    fluent-reader
    fzf
    gdu
    geteduroam
    geteduroam-cli
    git
    glib
    gparted
    gpu-screen-recorder
    gpu-screen-recorder-gtk
    grsync
    gst_all_1.gstreamer
    gst_all_1.gst-vaapi
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-base
    handy
    helium
    heroic
    home-manager
    htop
    hugo
    hydralauncher
    hyprism
    hyprpicker
    input-remapper
    jq
    just
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.gwenview
    kdePackages.okular
    kdePackages.partitionmanager
    kdiskmark
    kitty
    legendary-gl
    libva
    libva-utils
    lidarr
    livecaptions
    llm-agents.jules
    localsend
    man
    mangayomi
    mangohud
    mat2
    mcpelauncher-ui-qt
    micro
    mindustry-wayland
    motrix
    mousam
    mpv
    neovim
    nicotine-plus
    nix-init
    nix-update
    nixd
    nixpkgs-review
    ntfs3g
    nurl
    nyaa
    obs-studio
    onlyoffice-desktopeditors
    opencommit
    openrct2
    osu-beatmap-manager
    osu-lazer-bin
    packwiz
    prismlauncher
    protonplus
    pwvucontrol
    python3
    qbittorrent
    rPackages.stranslate
    rclone
    redeclipse
    retroarch
    rsync
    ryubing
    samira
    scrcpy
    shattered-pixel-dungeon
    shellcheck
    songrec
    spotdl
    spotify-player
    starship
    statix
    syncthing
    tealdeer
    telegram-desktop
    television
    textpieces
    thunderbird
    torrra
    turkanime-cli
    turkanime-gui
    umu-launcher
    upscayl
    vlc
    vscodium
    wdisplays
    wget
    wine-staging
    winetricks
    wl-clipboard
    wlr-randr
    xclip
    xdg-utils
    yazi
    yt-dlp
    zathura
    zip
    zoxide
  ];
}
