{
  pkgs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    # keep-sorted start case=no
    android-tools
    ani-cli
    anitr-cli
    antimicrox
    anup
    atuin
    audacity
    bats
    bedrock-on-linux
    better-control
    bolt-launcher
    brightnessctl
    btrfs-progs
    bubblewrap
    comma
    crankshaft
    crow-translate
    curl
    dash
    deadnix
    easyeffects
    efibootmgr
    exiftool
    eza
    fastfetch
    ffmpeg-full
    flameshot
    fluent-reader
    fzf
    gdu
    geteduroam
    geteduroam-cli
    git
    github-cli
    glib
    gowall
    gparted
    grsync
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gstreamer
    handy
    helium
    heroic
    home-manager
    htop
    hugo
    hydralauncher
    hyprpicker
    joplin-desktop
    jq
    just
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.gwenview
    kdePackages.okular
    kdePackages.partitionmanager
    kitty
    kopuz-flake
    legendary-gl
    libreoffice-fresh
    libva
    libva-utils
    lidarr
    livecaptions
    localsend
    man
    mangayomi
    mangohud
    manix
    mat2
    micro
    motrix-next
    mousam
    mpv
    mullvad-browser
    navi
    neovim
    nicotine-plus
    nix-fast-build
    nix-init
    nix-update
    nixd
    nixpkgs-review
    normcap
    ntfs3g
    nurl
    nvd
    nyaa
    onlyoffice-desktopeditors
    opencommit
    openrct2
    openutau
    optnix
    osu-beatmap-manager-git
    osu-lazer
    packwiz
    pdfarranger
    prismlauncher
    proton-vpn
    proton-vpn-cli
    protonplus
    pwvucontrol
    python3
    qbittorrent
    qtscrcpy
    rclone
    readest
    retroarch
    riseup-vpn
    rsync
    ryubing
    samira
    scrcpy
    shattered-pixel-dungeon
    shellcheck
    smassh
    songrec
    spotdl
    spotify-player
    starship
    statix
    subtitleedit
    syncthing
    tealdeer
    telegram-desktop
    television
    textpieces
    thunderbird
    tor
    tor-browser
    torrra
    turkanime-cli
    turkanime-gui
    umu-launcher
    upscayl
    vlc
    vscodium
    waytator
    wdisplays
    wget
    wine-staging
    winetricks
    wl-clipboard
    wlr-randr
    xclip
    xdg-utils
    yazi
    yt-dlp
    zathura
    zerotierone
    zip
    zotero
    zoxide
    # keep-sorted end
  ];
}
