keys:
  - &users:
        -  &aniviaflome age1fcsznz5k5qzgu2km7fn62xvl0jsws4p3ed6008rq0gkvefpnaa8qrl3cdx
  - &hosts:
        -  &nixos age1475tk86qd0gtqvve5dxn60fh70rqzm30cemrrgsx58nuk3lmqejqtmmsxf
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *aniviaflome
      - *nixos
