keys:
  - &users:
        -  &aniviaflome age1mw2ac4djr7s37kp3tgj92zxxe3svyw09q8pvy5ve8tchkdn2vqaqnw7qv4
  - &hosts:
        -  &nixos age1475tk86qd0gtqvve5dxn60fh70rqzm30cemrrgsx58nuk3lmqejqtmmsxf
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *aniviaflome
      - *nixos
