{
  imports = [
../../hm-modules/atuin.nix
../../hm-modules/bash.nix
../../hm-modules/catppuccin.nix
../../hm-modules/distrobox/default.nix
../../hm-modules/fastfetch/default.nix
../../hm-modules/fish.nix
../../hm-modules/git.nix
../../hm-modules/kitty.nix
../../hm-modules/mpv.nix
../../hm-modules/niri/default.nix
../../hm-modules/nvf.nix
../../hm-modules/nh.nix
../../hm-modules/plasma.nix
../../hm-modules/qutebrowser.nix
../../hm-modules/scripts/default.nix
../../hm-modules/spicetify.nix
../../hm-modules/starship.nix
../../hm-modules/theme.nix
../../hm-modules/tmux.nix
../../hm-modules/variables.nix
../../hm-modules/vscodium.nix
../../hm-modules/zen-browser/default.nix
../../hm-modules/zoxide.nix
  ];
}
