name: "Build ISO"
on:
  workflow_dispatch:
    inputs:
      iso:
        type: choice
        required: true
        description: "Which iso you want to build?"
        options:
          - "Normal"
          - "Minimal"
env:
  LIVEISO: ${{ github.event.inputs.iso == 'Minimal' && 'liveiso-minimal' || 'liveiso' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18

    - name: Build ISO
    - run: nix build .#${{ env.ARTIFACT_FINAL_NAME }}
    - run: tree result
    - uses: actions/upload-artifact@v4
      with:
        name: NixOS-${{ github.event.inputs.iso }}
        path: result/sd-image
